#!/bin/bash

# Last edit on Jul 11, 2017 - 18:45 PM  

IFS=$'\n'
LIST_OF_PRINTERS=$(/usr/bin/lpstat -p | awk '{print $2}')


for i in $LIST_OF_PRINTERS
do
  echo "disabling sharing on $i"
  /usr/sbin/lpadmin -p "$i" -o printer-is-shared=false
done

# disable the global printer sharing pref
echo "disable the global printer sharing preference"
/usr/sbin/cupsctl --no-share-printers

# end

