#!/bin/bash


current_user=$(ls -l /dev/console | awk '{print $3}') # gets current user name
echo "Current User is $current_user"
/usr/bin/defaults write /Users/$current_user/Library/Preferences/com.microsoft.office.plist DefaultsToLocalOpenSave true
result=$(/usr/bin/defaults read /Users/$current_user/Library/Preferences/com.microsoft.office.plist DefaultsToLocalOpenSave)
echo "DefaultsToLocalOpenSave is now set to $result"
exit 


